config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :animals, only: [ :index, :new, :create ] do
    resources :bookings, only: :create
  end
  resources :animals, only: :show do
    resources :reviews, only: [ :new, :create ]
  end
  resources :bookings, only: [ :index, :update, :edit, :destroy ]
  namespace :owner do
    resources :bookings, only: [ :index, :update ]
    resources :animals, only: :index
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_species_and_location_and_name,
    against: [ :species, :location, :name ],
    using: {
      tsearch: { prefix: true }
    }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  enum sex: { Unknown: 0, Male: 1, Female: 2 }
  enum rarity_level: { Threatened: 0, Endangered: 1, "Extinct in the Wild" => 2 }
  enum diet: { Herbivore: 0, Omnivore: 1, Carnivore: 2, Pescivore: 3, Insectivore: 4, Popcornivore: 5 }

  def average_rating
    reviews.blank? ? 0 : reviews.sum('rating') / reviews.count
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :animal
  belongs_to :user
  enum status: { pending: 0, confirmed: 1, denied: 2 }
  validate :end_date_after_start_date, :start_date_before_today

  def end_date_after_start_date
    errors.add(:end_date, "cannot be selected before start date!") if end_date <= start_date
  end

  def start_date_before_today
    errors.add(:start_date, "cannot be selected before today!") if start_date < Date.today
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :animal
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :animals
  has_many :reviews, dependent: :destroy
  has_many :bookings_as_owner, through: :animals, source: :bookings
  has_one_attached :photo
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @animals = policy_scope(Animal).search_by_species_and_location_and_name(params[:query])
    else
      @animals = policy_scope(Animal).order(created_at: :desc)
    end
  end

  def show
    @animal = Animal.find(params[:id])
    @booking = Booking.new
    @review = Review.new
    authorize @animal
    @markers = [
      {
        lat: @animal.latitude,
        lng: @animal.longitude,
        info_window: render_to_string(partial: 'animals/info_window', locals: { animal: @animal })
      }
    ]
  end

  def new
    @animal = Animal.new
    authorize @animal
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user = current_user
    authorize @animal

    if @animal.save
      redirect_to animals_path, notice: 'Listing was successfully created.'
    else
      render :new
    end
  end

  private

  def animal_params
    params.require(:animal).permit(:name, :species, :sex, :rarity_level, :age, :diet, :price, :location, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking).order(start_date: :desc)
    @markers = @bookings.map do |booking|
      {
        lat: booking.animal.latitude,
        lng: booking.animal.longitude,
        info_window: render_to_string(partial: 'animals/info_window', locals: { animal: booking.animal })
      }
    end
  end

  def create
    @booking = Booking.new(booking_params)
    @animal = Animal.find(params[:animal_id])
    @booking.animal = @animal
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to bookings_path, notice: 'Booking was successfully created. Please wait until the owner confirms'
    else
      render "animals/show"
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    # raise StandardError, 'NotAuthorized' unless @restaurant.user == current_user
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(booking_params)
      redirect_to bookings_path, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to bookings_url notice: "The booking was successfully deleted."
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user, :animal, :status)
  end
end

app/controllers/owner/animals_controller.rb
class Owner::AnimalsController < ApplicationController

  def index
    if params[:query].present?
      @animals = policy_scope(Animal).search_by_species_and_rarity_level(params[:query])
    else
      @animals = policy_scope(Animal.where(user_id: current_user.id))
    end
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  def index
    @bookings = policy_scope([:owner, Booking]).order(start_date: :desc)
  end

  def update
    # raise StandardError, 'NotAuthorized' unless @restaurant.user == current_user
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(booking_params)
      redirect_to owner_bookings_path, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user, :animal, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @animals = Animal.all.order(created_at: :desc)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = policy_scope(Review).order(created_at: :desc)
  end

  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @animal = Animal.find(params[:animal_id])
    @review.animal = @animal
    authorize @review

    if @review.save
      redirect_to animal_path(@animal), notice: 'Review was successfully created.'
    else
      @booking = Booking.new
      render "animals/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_info_window.html.erb
<div class="container">
  <h2><%= animal.name %></h2>
  <p class="fs-5 text">📍<%= animal.location %></p>
</div>

app/views/animals/index.html.erb
<div class="banner" style="background-image: url(https://i.gifer.com/DFBC.gif);">
  <div class="container">
    <h2>Need something?</h2>
    <div class="row">
      <div class="col col-sm-6 col-md-4">
        <%= render "shared/search" %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="cards">
    <% @animals.each do |animal| %>
      <div class="card-trip">
        <%# <%= cl_image_tag animal.photo.key, height: 300, width: 400, crop: :fill %>
        <img src='<%= animal.photo.attached? ? cl_image_path(animal.photo.key) : "https://mycountrysidevet.com/wp-content/uploads/2018/08/shutterstock_1043006710.jpg" %>' />
        <%# <img src="https://mycountrysidevet.com/wp-content/uploads/2018/08/shutterstock_1043006710.jpg" /> %>
        <div class="card-trip-infos">
          <div>
            <h2><strong><%= link_to animal.name, animal_path(animal), class:"text-decoration-none", style:"color: green;"%></strong>
              <% if animal.sex == "Unknown" %>
                <i class="fas fa-genderless" style="color: gold;"></i>
              <% elsif animal.sex == "Male" %>
                <i class="fas fa-mars" style="color: blue;"></i>
              <% else %>
                <i class="fas fa-venus" style="color: hotpink;"></i>
              <% end %>
            </h2>
            <p><strong><%= animal.species %></strong></p>
            <% if animal.rarity_level == "Threatened" %>
              <p>Threatened <i class="fas fa-times-circle" style="color: green;"></i></p>
            <% elsif animal.rarity_level == "Endangered" %>
              <p>Endangered <i class="fas fa-exclamation-triangle" style="color: gold;"></i></p>
            <% else %>
              <p>Extinct in the Wild <i class="fas fa-skull-crossbones" style="color: black;"></i></p>
            <% end %>
          </div>
          <div class="text-end">
            <div class="d-flex mb-3">
              <% animal.average_rating.times do %>
                <i class="fas fa-star"></i>
              <% end %>
              <% (5 - animal.average_rating).times do %>
                <i class="far fa-star"></i>
              <% end %>
            </div>
            <h2 class="card-trip-pricing">$<%= animal.price %>/day</h2>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="footer">
  <div class="footer-links">
    <a href="https://worldbirds.com/wp-content/uploads/2020/05/unicorn3.jpg"><i class="fab fa-github"></i></a>
    <a href="https://animalcorner.org/wp-content/uploads/2015/02/racoon.png"><i class="fab fa-instagram"></i></a>
    <a href="https://cdn-japantimes.com/wp-content/uploads/2014/10/f-cheetahs-a-20141004.jpg"><i class="fab fa-facebook"></i></a>
    <a href="https://ichef.bbci.co.uk/news/976/cpsprodpb/793E/production/_117883013_gorilla_dianfosseygorillafund1.jpg"><i class="fab fa-twitter"></i></a>
    <a href="https://cdn.wallpapersafari.com/11/95/QqDp5C.jpg"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fas fa-heart"></i> Exoticals
  </div>
</div>

app/views/animals/new.html.erb
<div class="banner" style="background-image: url(https://i.imgur.com/5oQYvVL.gif?noredirect);">
  <div class="container">
    <h1><strong>Create Listing</strong></h1>
  </div>
</div>
</div>
<div class="container mt-3 mb-4">
  <%= simple_form_for [@animal] do |f| %>
    <%= f.input :name %>
    <%= f.input :species %>
    <%= f.input :sex, collection: Animal.sexes.keys %>
    <%= f.input :rarity_level, collection: Animal.rarity_levels.keys %>
    <%= f.input :age, collection: (0..100) %>
    <%= f.input :diet, collection: Animal.diets.keys %>
    <%= f.input :location %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, "Create", class: "btn btn-flat mt-3" %>
  <% end %>
</div>

app/views/animals/show.html.erb
<div data-controller="calculation" class="container-md mt-5">
  <div class="row">
    <div class="col-12 col-md-8">
      <div class="d-flex justify-content-center mt-4">
        <div class="card-trip" id="card-show">
          <img id="img-show" src='<%= @animal.photo.attached? ? cl_image_path(@animal.photo.key) : "https://mycountrysidevet.com/wp-content/uploads/2018/08/shutterstock_1043006710.jpg" %>' />
          <div class="card-trip-infos">
            <div>
              <h1 style="color: green;"></strong><%= @animal.name %>
              <% if @animal.sex == "Unknown" %>
                <i class="fas fa-genderless" style="color: gold;"></i>
              <% elsif @animal.sex == "Male" %>
                <i class="fas fa-mars" style="color: blue;"></i>
              <% else %>
                <i class="fas fa-venus" style="color: hotpink;"></i>
              <% end %>
            </h1>
            <h4><%= @animal.species %></h4>
            <p><strong>Age:</strong> <%= @animal.age %> years</p>
            <% if @animal.rarity_level == "Threatened" %>
              <p>Threatened <i class="fas fa-times-circle" style="color: green;"></i></p>
            <% elsif @animal.rarity_level == "Endangered" %>
              <p>Endangered <i class="fas fa-exclamation-triangle" style="color: gold;"></i></p>
            <% else %>
              <p>Extinct in the Wild <i class="fas fa-skull-crossbones" style="color: black;"></i></p>
            <% end %>
            <p><%= @animal.species.pluralize %> are <strong><%= @animal.diet %>s</strong></p>
          </div>
          <div class="text-end">
            <div class="d-flex mb-3">
              <% @animal.average_rating.times do %>
                <i class="fas fa-star"></i>
              <% end %>
              <% (5 - @animal.average_rating).times do %>
                <i class="far fa-star"></i>
              <% end %>
            </div>
            <h2 class="card-trip-pricing">$<%= @animal.price %>/day</h2>
          </div>
          <%# <img src="https://kitt.lewagon.com/placeholder/users/yannklein" class="card-trip-user avatar-bordered" /> %>
          <img src='<%= @animal.user.photo.attached? ? cl_image_path(@animal.user.photo.key) : "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" %>' class="card-trip-user avatar-bordered" />
        </div>
      </div>
    </div>
  </div>
  <div class="col-12 col-md-4 mt-4 mb-4">
    <div style="border: 1px solid rgb(221, 221, 221); border-radius: 12px; padding: 24px; box-shadow: rgba(0, 0, 0, 0.12) 0px 6px 16px; background-color: white;">
      <h3>Ready to book?</h3>
      <%= simple_form_for [ @animal, @booking ] do |f| %>
        <%= f.input :start_date, html5: true, input_html: {data: {calculation_target:"startDay", action: "change->calculation#calculate"} } %>
        <%= f.input :end_date, html5: true, input_html: {data: {calculation_target:"endDay", action: "change->calculation#calculate"} }  %>
        <%= f.submit class:"btn btn-flat"%>
      <% end %>
    </div>
    <div style="border: 1px solid rgb(221, 221, 221); border-radius: 12px; padding: 24px; box-shadow: rgba(0, 0, 0, 0.12) 0px 6px 16px; background-color: white;">
      <div class="text-end">
        <h3 class="text-start">Your Cart</h3>
        <h5 class="mt-3"><%= @animal.name %> (<%= @animal.species %>)</h5>
        <p>$ <span data-calculation-target="price"> <%= @animal.price %> </span> x <span data-calculation-target="days">1</span> </p>
        <h3 >Total <strong>$ <span data-calculation-target="total"> <%= @animal.price %></strong></span></h3>
      </div>
    </div>
  </div>
</div>
<div>
  <% @animal.reviews.each do |review| %>
    <div class="card-product mt-3 mb-4">
      <div class="card-info">
        <img src='<%= review.user.photo.attached? ? cl_image_path(review.user.photo.key) : "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png" %>' />
        <div class="card-product-infos">
          <div class="d-flex">
            <% review.rating.times do %>
              <i class="fas fa-star"></i>
            <% end %>
            <% (5 - review.rating).times do %>
              <i class="far fa-star"></i>
            <% end %>
          </div>
          <p><%= review.created_at.strftime('%Y-%m-%d') %></p>
          <p><strong><%= review.content %></strong></p>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="mt-5">
  <h3>Leave a Review</h3>
  <%= simple_form_for [ @animal, @review ], class:"pt-5" do |f| %>
    <div class="star-rating">
      <% 5.times do |i| %>
        <input type="radio" name="review[rating]" value="<%= i + 1 %>" <%= "checked" if i == 2 %> />
      <% end %>
    </div>
    <%= f.input :content, label: false, style:"color: white;", input_html: { minlength: 20, class:"review-input" }  %>
    <%= f.button :submit, class:"btn btn-flat"%>
  <% end %>
</div>
<h2 class="mt-5">Where <%= @animal.name %> is located</h2>
<div class="cards mb-5" style="width: 100%; height: 600px;"

      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
</div>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>
<div class="container mt-3 mb-4">
  <%= simple_form_for @booking do |f| %>
      <%= f.input :start_date, html5: true %>
      <%= f.input :end_date, html5: true %>
      <%= f.submit %>
  <% end %>
</div>
<%= link_to 'Back', :back, class: "btn btn-info btn-md ms-3" %>

app/views/bookings/index.html.erb
<div class="banner" style="background-image: url(http://media.giphy.com/media/6xLapD0nWE4ZG/giphy.gif);">
  <div class="container">
    <h1><strong>Your Bookings</strong></h1>
  </div>
</div>
</div>
<div class="container">
  <% @bookings.each do |booking| %>
    <div class="card-product mt-3 mb-4">
      <div class="card-info">
        <img src='<%= booking.animal.photo.attached? ? cl_image_path(booking.animal.photo.key) : "https://mycountrysidevet.com/wp-content/uploads/2018/08/shutterstock_1043006710.jpg" %>' />
        <div class="card-product-infos d-flex row p-3">
          <div class="d-grid">
            <div class="container mt-3">
              <h2><%= booking.animal.name %></h2>
            </div>
            <div class="d-flex justify-content-evenly">
              <i class="far fa-calendar-alt me-3"></i>
              <h2 class="me-1"><%= booking.start_date.strftime("%B %d") %></h2>
              <h2>- <%= booking.end_date.strftime("%B %d") %></h2>
            </div>
          </div>
        </div>
      </div>
      <div class="card-product-infos d-grid gap-2">
        <div class="btn <%= booking.status == "confirmed" ? "btn-success" : "btn-info"%> btn-sm"><%= booking.status.capitalize %></div>
        <%= link_to "Edit", edit_booking_path(booking), class: "btn btn-primary btn-sm"%>
        <%= link_to "Cancel", booking_path(booking), method: :delete, data: { confirm: "Are you sure you'd like to cancel this booking?" }, class: "btn btn-danger btn-sm"%>
      </div>
    </div>
  <% end %>
</div>

<div class="container">
  <h2 class="mt-5">Where booked animals are located</h2>
  <div class="cards mb-5" style="width: 100%; height: 600px;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exoticals</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/owner/animals/index.html.erb
<div class="banner" style="background-image: url(https://i.pinimg.com/originals/41/9c/39/419c392ff69dd5e092c780719e72566d.gif);">
  <div class="container">
    <h1><strong>My Listings</strong></h1>
    <div class="row">
      <div class="col col-sm-6 col-md-4">
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="cards">
    <% @animals.each do |animal| %>
      <div class="card-trip">
        <%# <%= cl_image_tag animal.photo.key, height: 300, width: 400, crop: :fill %>
        <img src='<%= animal.photo.attached? ? cl_image_path(animal.photo.key) : "https://mycountrysidevet.com/wp-content/uploads/2018/08/shutterstock_1043006710.jpg" %>' />
        <%# <img src="https://mycountrysidevet.com/wp-content/uploads/2018/08/shutterstock_1043006710.jpg" /> %>
        <div class="card-trip-infos">
          <div>
            <h2><%= link_to animal.name, animal_path(animal), class:"text-decoration-none"%></h2>
            <p><%= animal.species %></p>
            <p><%= animal.rarity_level %></p>
          </div>
          <h2 class="card-trip-pricing">$<%= animal.price %></h2>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="footer">
  <div class="footer-links">
    <a href="https://worldbirds.com/wp-content/uploads/2020/05/unicorn3.jpg"><i class="fab fa-github"></i></a>
    <a href="https://animalcorner.org/wp-content/uploads/2015/02/racoon.png"><i class="fab fa-instagram"></i></a>
    <a href="https://cdn-japantimes.com/wp-content/uploads/2014/10/f-cheetahs-a-20141004.jpg"><i class="fab fa-facebook"></i></a>
    <a href="https://ichef.bbci.co.uk/news/976/cpsprodpb/793E/production/_117883013_gorilla_dianfosseygorillafund1.jpg"><i class="fab fa-twitter"></i></a>
    <a href="https://cdn.wallpapersafari.com/11/95/QqDp5C.jpg"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fas fa-heart"></i> Exoticals
  </div>
</div>

app/views/owner/bookings/index.html.erb
<div class="banner" style="background-image: url(https://media.baamboozle.com/uploads/images/452366/1629644076_111411_gif-url.gif);">
  <div class="container">
    <h1><strong>Client Bookings</strong></h1>
  </div>
</div>
</div>
<div class="container">
  <% @bookings.each do |booking| %>
    <div class="card-product mt-3 mb-4">
      <div class="card-info">
        <img src='<%= booking.animal.photo.attached? ? cl_image_path(booking.animal.photo.key) : "https://mycountrysidevet.com/wp-content/uploads/2018/08/shutterstock_1043006710.jpg" %>' />
        <div class="card-product-infos d-flex row p-3">
          <div class="d-grid mb-3">
            <div class="container mt-3">
              <h2>Client Name: <%= booking.user.first_name.capitalize %></h2>
              <h2>Animal Name: <%= booking.animal.name.capitalize %></h2>
              <h2>Status: <%= booking.status.capitalize %></h2>
            </div>
            <div class="d-flex justify-content-evenly">
              <i class="far fa-calendar-alt me-3"></i>
              <h2 class="me-1"><%= booking.start_date.strftime("%B %d") %></h2>
              <h2>- <%= booking.end_date.strftime("%B %d") %></h2>
            </div>
          </div>
        </div>
      </div>
      <div class="card-product-infos d-grid">
        <%= simple_form_for booking, url: owner_booking_path(booking) do |f| %>
          <%= f.input :status, as: :hidden, input_html: { value: 'confirmed'} %>
          <%= f.submit 'Confirm', class: 'btn btn-primary' %>
        <% end %>
        <%= simple_form_for booking, url: owner_booking_path(booking) do |f| %>
          <%= f.input :status, as: :hidden, input_html: { value: 'denied'} %>
          <%= f.submit 'Decline', class: 'btn btn-info' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="video">
  <video autoplay muted loop id="myVideo" style="width: 100%">
    <source src="https://cdn.videvo.net/videvo_files/video/free/2019-11/small_watermarked/190301_1_25_10_preview.webm" type="video/webm">
  </video>
  <div class="overlayText">
    <div class="d-flex align-items-center h-100 flex-column pt-5 mt-5">
    <h1><strong>Exoticals</strong></h1>
    <p>Find your animal!</p>
    <%= link_to "Enter", animals_path, class: "btn btn-flat" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://png.pngtree.com/png-vector/20190925/ourlarge/pngtree-tiger-face-logo-png-image_1743050.jpg" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <strong><%= link_to "Animals", animals_path, class: "nav-link" %></strong>
        </li>
        <li class="nav-item active">
          <strong><%= link_to "New Listing", new_animal_path, class: "nav-link" %></strong>
        </li>
        <li class="nav-item">
          <strong><%= link_to "Bookings", bookings_path, class: "nav-link" %></strong>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <strong><%= link_to "Roars", "https://gamingsection.net/wp-content/uploads/2022/03/Is-Lions-Roar-good-for-Keqing.jpg", class: "nav-link" %></strong>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag (current_user.photo.attached? ? cl_image_path(current_user.photo.key) : "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "My Listings", owner_animals_path, class: "dropdown-item" %>
              <%= link_to "Client Bookings", owner_bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <strong><%= link_to "Login", new_user_session_path, class: "nav-link" %></strong>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<%= simple_form_for :animals, url: animals_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="query" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i>
    </button>
  </div>
<% end %>